export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const INVALID_LOGIN_CREDENTIALS = 'INVALID_LOGIN_CREDENTIALS';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';


export const COOKIE_TOKEN_NAME = 'Token';
