// AUTH ACTIONS
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const INVALID_LOGIN_CREDENTIALS = 'INVALID_LOGIN_CREDENTIALS';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';

// USER ACTIONS
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTACTED_USER';
export const SET_AUTHENTICATION_ERROR = 'SET_AUTHENTICATION_ERROR';
export const SET_UNAUTHENTICATED_USER = 'SET_UNAUTHENTICATED_USER';

// SOCKET ACTIONS
export const SOCKET_CREATED = 'SOCKET_CREATED';
export const PLAYER_LIST = 'PLAYER_LIST';

// OTHER CONSTANTS
export const COOKIE_TOKEN_NAME = 'Token';
