# Generated by Django 2.2.2 on 2019-08-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('small_blind', models.PositiveIntegerField()),
                ('big_blind', models.PositiveIntegerField()),
                ('hand_count', models.BigIntegerField()),
                ('average_pot', models.FloatField()),
                ('max_players', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('C', 'Cash'), ('T', 'Tournament')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('W', 'Waiting'), ('C', 'Closed')], max_length=1)),
            ],
        ),
    ]
