# Generated by Django 2.2.2 on 2019-08-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table_name',
            new_name='name',
        ),
    ]
