# Generated by Django 2.2.4 on 2019-09-24 21:59

import core.models.validators.json_schema_validator
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190901_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='bb_seat',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='dealer_seat',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='sb_seat',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hand',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[core.models.validators.json_schema_validator.JsonSchemaValidator(schema='hand_history_schema')]),
        ),
    ]
